#!/bin/bash

setxkbmap -option -option caps:backspace -option shift:both_capslock -option numpad:mac

mkdir -p $HOME/.xkb/keymap
setxkbmap -print | sed -e '/xkb_symbols/s/"[[:space:]]/+local&/' > $HOME/.xkb/keymap/custom
xkbcomp -w0 -I$HOME/.xkb/ -R$HOME/.xkb/ keymap/custom $DISPLAY

synclient \
	TapButton1=0 TapButton2=0 \
	RightButtonArea{Left,Right,Top,Bottom}=0 \
	VertEdgeScroll=0 \
	HorizTwoFingerScroll=1 HorizScrollDelta=20 \
	CoastingSpeed=5 CoastingFriction=30
