#!/bin/bash

setxkbmap -option -option caps:backspace -option shift:both_capslock -option numpad:mac

mkdir -p $HOME/.xkb/keymap
setxkbmap -print | sed -e '/xkb_symbols/s/"[[:space:]]/+local&/' > $HOME/.xkb/keymap/custom
xkbcomp -w0 -I$HOME/.xkb/ -R$HOME/.xkb/ keymap/custom $DISPLAY

which xsri >/dev/null && xsri --tile=$HOME/Pictures/leave-it.png || xsetroot -solid darkgreen

synclient \
  TapButton1=0 TapButton2=0 \
  RightButtonArea{Left,Right,Top,Bottom}=0 \
  VertEdgeScroll=0 \
  HorizTwoFingerScroll=1 \
  TouchpadOff=1 ClickFinger1=0 ClickFinger2=0  # as in toggle-trackpad
